### ISSUE TITLE
Error instrumenting bluebird

### ISSUE THREAD

**Issue by sanji-programmer** [ValYouW/njsTrace#13]
I just got an error trying to use njstrace with bluebird. I set up a small project to reproduce the error in https://github.com/sanji-programmer/njstrace-bluebird-issue

The error is: 

ReferenceError: __njsEntryData__ is not defined
    at Object.<anonymous> (/home/sanji/git/njstrace-bluebird-issue/node_modules/bluebird/js/release/util.js:999:34)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/home/sanji/git/njstrace-bluebird-issue/node_modules/njstrace/njsTrace.js:158:15)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/home/sanji/git/njstrace-bluebird-issue/node_modules/bluebird/js/release/promise.js:66:12)
npm ERR! Test failed.  See above for more details.

**Comment by sanji-programmer** [comment]
I found the issue. File util.js of bluebird has a code like:
`...
try {throw new Error(); } catch (e) {ret.lastLineError = e;}
module.exports = ret;
`
njsTrace instruments the try clause and seems to introduce a reference to ` __njsEntryData__` that does not exist. I think the instrumentation is not supposed to be performed outside function scope.

A not-so-great workaround is to verify if ` __njsEntryData__` is defined ( Line 7 of injector.js ):
`var ON_CATCH = 'if (__njsOnCatchClause__) {\nif (typeof __njsEntryData__ !== "undefined") __njsOnCatchClause__({entryData: __njsEntryData__});\n}';`

**Comment by ValYouW** [comment]
Not sure I follow, I'll try to debug and see..

**Comment by sanji-programmer** [comment]
I isolated the problem (based on the bluebird util.js); if there is a module like: 
```
let ret = {}

try {
    throw new Error();
} catch (e) {
    ret.lastLineError = e;
}

module.exports = ret;
```
njsTrace will fail (see https://github.com/sanji-programmer/njstrace-bluebird-issue/blob/master/test-fakemod.js).

**Comment by ValYouW** [comment]
@sanji-programmer Indeed it happens because njsTrace is injecting all "catch" clauses (to report if there was an exception), but obviously it shouldn't inject catch clauses on the "top-level wrapper function" (the function that Node.js is wrapping all modules with).
Note that this crash would have also happened if there was a "return" statement on the top-level module code...
Thx

**Comment by sanji-programmer** [comment]
Thank you very much for the fix!
