### ISSUE TITLE
Async call handling

### ISSUE THREAD

**Issue by deepalitandel** [ValYouW/njsTrace#7]
How does NJSTrace handle async call?

**Comment by ValYouW** [comment]
Not sure I understand the question.

**Comment by drv1234** [comment]
hi,
could you please help me? It seems async is not supported.
If I change the example file to this, exception happens when I try to run.

// *** mymod.js ***
exports.run = async function(number) {
    number = await first(number);
    printResult(number);
}
:
:

**Comment by drv1234** [comment]
I use the latest node js. Without njstrace instrment the code runs fine.

**Comment by drv1234** [comment]
here is the printout:

njsTrace: New instance of NJSTrace created with config: { enabled: true,
  files: [ '**/*.js', '!**/node_modules/**' ],
  wrapFunctions: false,
  logger: true,
  inspectArgs: true }
njsTrace: Creating new Injector and hijacking Module.prototype._compile
njsTrace: Setting global.__njsTraceEntry__ function
njsTrace: Setting global.__njsTraceExit__ function
njsTrace: Setting global.__njsOnCatchClause__ function
njsTrace: njsTrace done loading...
njsTrace: Instrumenting: c:\temp\mymod.js
njsTrace: ERROR: Error instrumenting file: c:\temp\mymod.js , Exception: { Error: Line 3: Unexpected token function
    at throwError (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:1467:21)
    at throwUnexpected (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:1521:13)
    at consumeSemicolon (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:1605:13)
    at parseStatement (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:2853:9)
    at c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:3588:38
    at parseSourceElement (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:3073:20)
    at parseFunctionSourceElements (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:2905:29)
    at c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:3588:38
    at parseFunctionExpression (c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:3045:16)
    at c:\temp\node_modules\falafel\node_modules\esprima\esprima.js:3588:38
  index: 104,
  lineNumber: 3,
  column: 21,
  description: 'Unexpected token function' }
c:\temp\main.js:10
mymod.run(parseFloat(Math.random().toFixed(4)));
      ^

TypeError: mymod.run is not a function
    at Object.<anonymous> (c:\temp\main.js:10:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by ValYouW** [comment]
I know async await is suppurted in Nodejs, it is not supported by the library I am using to parse the javascript files (at lease in the way I'm currently doing it)

**Comment by drv1234** [comment]
Thanks.
Are you planning to support it in the near future? 
Or shall I find other ways?

**Comment by ValYouW** [comment]
It is really up to whether [this](https://www.npmjs.com/package/acorn) library supports it, if it does it should be relatively easy to support it. I'll try to find some time to check it on the weekend

**Comment by drv1234** [comment]
hi,
thanks, I tried on my project and it works like a charm.

But...
The named (optional) parameters are not printed even if they are in the caller line.
I don't know is it up to you or it comes from external lib.
(unfortunately there are a lot of this kind of function in my project, because it is a test framework and it is continuously developed but older test are not modified)

To see, modify the example:

// *** main.js 
:
mymod.run(parseFloat(Math.random().toFixed(4)), xx=11);

// *** mymod.js ***
exports.run = async function (number, xx=22) {
